config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/flaat:
      branch: master
      repo: https://github.com/indigo-dc/flaat
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/flaat git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-green-bulldog.sh
        container: qc.acc_grumpy-chestnut-skunk
  QC.Doc:
    repos:
      github.com/indigo-dc/flaat find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-ruby-mandrill.sh
        container: qc.doc_gloppy-aquamarine-kakapo
      github.com/indigo-dc/flaat git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-mauve-robin.sh
        container: qc.doc_whiny-mustard-mammoth
      github.com/indigo-dc/flaat markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-viridian-newfoundland.sh
        container: qc.doc_snappy-gamboge-dane
      github.com/indigo-dc/flaat restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-linen-frise.sh
        container: qc.doc_tacky-celadon-gopher
  QC.Lic:
    repos:
      github.com/indigo-dc/flaat licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-wheat-orangutan.sh
        container: qc.lic_silly-cinnamon-akita
  QC.Sec:
    repos:
      github.com/indigo-dc/flaat bandit:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-gamboge-fossa.sh
        container: qc.sec_scanty-salmon-flamingo
  QC.Sty:
    repos:
      github.com/indigo-dc/flaat flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-thistle-moth.sh
        container: qc.sty_blurry-pear-toucan
  QC.Ver:
    repos:
      github.com/indigo-dc/flaat get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-vermilion-cassowary.sh
        container: qc.ver_baggy-ochre-guppy
timeout: 5400
