config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/flaat:
      branch: master
      repo: https://github.com/indigo-dc/flaat
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/flaat git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-blue-sheepdog.sh
        container: qc.acc_greasy-saffron-bandicoot
  QC.Doc:
    repos:
      github.com/indigo-dc/flaat find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-olive-insect.sh
        container: qc.doc_jumpy-salmon-vulture
      github.com/indigo-dc/flaat git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-white-mongrel.sh
        container: qc.doc_flaky-thistle-neanderthal
      github.com/indigo-dc/flaat markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-coral-bombay.sh
        container: qc.doc_bluesy-amber-beetle
      github.com/indigo-dc/flaat restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-gamboge-monster.sh
        container: qc.doc_thirsty-burgundy-starfish
  QC.Lic:
    repos:
      github.com/indigo-dc/flaat licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-vermilion-butterfly.sh
        container: qc.lic_sunny-coral-falcon
  QC.Sec:
    repos:
      github.com/indigo-dc/flaat bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-amethyst-mouse.sh
        container: qc.sec_snoopy-ruby-barracuda
  QC.Sty:
    repos:
      github.com/indigo-dc/flaat flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-ivory-baboon.sh
        container: qc.sty_wheezy-smalt-tarsier
  QC.Ver:
    repos:
      github.com/indigo-dc/flaat get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-malachite-tzu.sh
        container: qc.ver_foggy-saffron-dunker
timeout: 5400
