config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/flaat:
      branch: master
      repo: https://github.com/indigo-dc/flaat
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/flaat git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-cinnamon-wrasse.sh
        container: qc.acc_scummy-sepia-capuchin
  QC.Doc:
    repos:
      github.com/indigo-dc/flaat find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-xanthic-collie.sh
        container: qc.doc_lousy-cardinal-oriole
      github.com/indigo-dc/flaat git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-wisteria-turkey.sh
        container: qc.doc_stealthy-black-tarsier
      github.com/indigo-dc/flaat markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-sapphire-ostrich.sh
        container: qc.doc_smelly-firebrick-jellyfish
      github.com/indigo-dc/flaat restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-beige-lobster.sh
        container: qc.doc_leaky-razzmatazz-hare
  QC.Lic:
    repos:
      github.com/indigo-dc/flaat licensee:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-seashell-tapir.sh
        container: qc.lic_wiggy-pear-setter
  QC.Sec:
    repos:
      github.com/indigo-dc/flaat bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-periwinkle-barnacle.sh
        container: qc.sec_cheeky-xanthic-capybara
  QC.Sty:
    repos:
      github.com/indigo-dc/flaat flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-mustard-quetzal.sh
        container: qc.sty_nerdy-magenta-bracke
  QC.Ver:
    repos:
      github.com/indigo-dc/flaat get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-seashell-starfish.sh
        container: qc.ver_wimpy-ochre-drever
timeout: 5400
