config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/flaat:
      branch: master
      repo: https://github.com/indigo-dc/flaat
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/flaat git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-razzmatazz-mist.sh
        container: qc.acc_homely-amber-donkey
  QC.Doc:
    repos:
      github.com/indigo-dc/flaat find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-teal-newt.sh
        container: qc.doc_scummy-sapphire-snail
      github.com/indigo-dc/flaat git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-lime-argentino.sh
        container: qc.doc_cozy-olivine-frog
      github.com/indigo-dc/flaat markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-wheat-corgi.sh
        container: qc.doc_trippy-platinum-dane
      github.com/indigo-dc/flaat restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-jade-chin.sh
        container: qc.doc_sleepy-grey-angelfish
  QC.Lic:
    repos:
      github.com/indigo-dc/flaat licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-beige-vulture.sh
        container: qc.lic_grumpy-lime-chinchilla
  QC.Sec:
    repos:
      github.com/indigo-dc/flaat bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-sangria-squirt.sh
        container: qc.sec_slimy-zucchini-spitz
  QC.Sty:
    repos:
      github.com/indigo-dc/flaat flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-brown-leopard.sh
        container: qc.sty_squirrely-harlequin-snake
  QC.Ver:
    repos:
      github.com/indigo-dc/flaat get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-lilac-vulture.sh
        container: qc.ver_whiny-amber-hornet
timeout: 5400
